// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using pulaVocab.Infrastructure;

#nullable disable

namespace pulaVocab.Infrastructure.Migrations
{
    [DbContext(typeof(VocabMasterDbContext))]
    [Migration("20260809193000_AddPracticeModule")]
    partial class AddPracticeModule
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("pulaVocab.Domain.Entities.EnglishWordDetails", b =>
                {
                    b.Property<Guid>("VocabularyEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("vocabulary_entry_id");

                    b.Property<string>("Gerund")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("gerund");

                    b.Property<string>("Infinitive")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("infinitive");

                    b.Property<bool>("IsIrregularVerb")
                        .HasColumnType("boolean")
                        .HasColumnName("is_irregular_verb");

                    b.Property<string>("PastParticiple")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("past_participle");

                    b.Property<string>("PastTense")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("past_tense");

                    b.Property<string>("RelatedPhrasalVerbs")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("related_phrasal_verbs");

                    b.Property<string>("ThirdPersonSingular")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("third_person_singular");

                    b.HasKey("VocabularyEntryId");

                    b.ToTable("english_word_details", (string)null);
                });

            modelBuilder.Entity("pulaVocab.Domain.Entities.ExampleSentence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Explanation")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("explanation");

                    b.Property<bool>("IsGeneratedByAi")
                        .HasColumnType("boolean")
                        .HasColumnName("is_generated_by_ai");

                    b.Property<string>("Sentence")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("sentence");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("translation");

                    b.Property<Guid>("VocabularyEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("vocabulary_entry_id");

                    b.HasKey("Id");

                    b.HasIndex("VocabularyEntryId");

                    b.ToTable("example_sentences", (string)null);
                });

            modelBuilder.Entity("pulaVocab.Domain.Entities.GermanWordDetails", b =>
                {
                    b.Property<Guid>("VocabularyEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("vocabulary_entry_id");

                    b.Property<string>("Article")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("article");

                    b.Property<string>("AuxiliaryVerb")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("auxiliary_verb");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<string>("GoverningCase")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("governing_case");

                    b.Property<bool>("IsSeparableVerb")
                        .HasColumnType("boolean")
                        .HasColumnName("is_separable_verb");

                    b.Property<string>("PastParticiple")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("past_participle");

                    b.Property<string>("Plural")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("plural");

                    b.Property<string>("SeparablePrefix")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("separable_prefix");

                    b.HasKey("VocabularyEntryId");

                    b.ToTable("german_word_details", (string)null);
                });

            modelBuilder.Entity("pulaVocab.Domain.Entities.PracticeAnswer", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Answer").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<DateTime>("AnsweredAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<int>("AttemptNumber").HasColumnType("integer");
                    b.Property<int>("ExerciseType").HasColumnType("integer");
                    b.Property<bool>("IsCorrect").HasColumnType("boolean");
                    b.Property<Guid>("PracticeSessionId").HasColumnType("uuid");
                    b.Property<long?>("ResponseTimeMilliseconds").HasColumnType("bigint");
                    b.Property<Guid>("VocabularyEntryId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("VocabularyEntryId");
                    b.HasIndex("PracticeSessionId", "VocabularyEntryId", "AttemptNumber").IsUnique();
                    b.ToTable("practice_answers", (string)null);
                });

            modelBuilder.Entity("pulaVocab.Domain.Entities.PracticeSession", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<int>("CorrectCount").HasColumnType("integer");
                    b.Property<long?>("DurationMilliseconds").HasColumnType("bigint");
                    b.Property<int>("ExerciseType").HasColumnType("integer");
                    b.Property<string>("FiltersJson").IsRequired().HasColumnType("jsonb");
                    b.Property<DateTime?>("FinishedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<int>("IncorrectCount").HasColumnType("integer");
                    b.Property<int>("Language").HasColumnType("integer");
                    b.Property<Guid?>("ParentSessionId").HasColumnType("uuid");
                    b.Property<int>("PracticedCount").HasColumnType("integer");
                    b.Property<int>("ScheduledCount").HasColumnType("integer");
                    b.Property<DateTime>("StartedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<int>("Status").HasColumnType("integer");
                    b.Property<Guid?>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("Status");
                    b.HasIndex("UserId", "StartedAtUtc");
                    b.ToTable("practice_sessions", (string)null);
                });

            modelBuilder.Entity("pulaVocab.Domain.Entities.WordPracticeProgress", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<int>("CorrectCount").HasColumnType("integer");
                    b.Property<int>("CorrectStreak").HasColumnType("integer");
                    b.Property<DateTime?>("FirstReviewedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<int>("IncorrectCount").HasColumnType("integer");
                    b.Property<double>("IntervalDays").HasColumnType("double precision");
                    b.Property<int?>("LastExerciseType").HasColumnType("integer");
                    b.Property<int?>("LastRating").HasColumnType("integer");
                    b.Property<DateTime?>("LastReviewedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<int>("MasteryLevel").HasColumnType("integer");
                    b.Property<DateTime?>("NextReviewAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<Guid?>("UserId").HasColumnType("uuid");
                    b.Property<Guid>("VocabularyEntryId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("NextReviewAtUtc");
                    b.HasIndex("VocabularyEntryId").IsUnique();
                    b.HasIndex("UserId", "VocabularyEntryId").IsUnique();
                    b.ToTable("word_practice_progress", (string)null);
                });

            modelBuilder.Entity("pulaVocab.Domain.Entities.VocabularyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Antonyms")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("antonyms");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Ipa")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ipa");

                    b.Property<string>("IpaAmerican")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ipa_american");

                    b.Property<string>("IpaBritish")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ipa_british");

                    b.Property<int>("Language")
                        .HasColumnType("integer")
                        .HasColumnName("language");

                    b.Property<int?>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("cefr_level");

                    b.Property<string>("NormalizedTerm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_term");

                    b.Property<int?>("PartOfSpeech")
                        .HasColumnType("integer")
                        .HasColumnName("part_of_speech");

                    b.Property<string>("PersonalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("personal_notes");

                    b.Property<string>("Pronunciation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("pronunciation");

                    b.Property<string>("RelatedTerms")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("related_terms");

                    b.Property<string>("Source")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Synonyms")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("synonyms");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("term");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Language")
                        .HasDatabaseName("ix_vocabulary_entries_language");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_vocabulary_entries_status");

                    b.HasIndex("Term")
                        .HasDatabaseName("ix_vocabulary_entries_term");

                    b.HasIndex("Language", "NormalizedTerm")
                        .IsUnique()
                        .HasDatabaseName("ix_vocabulary_entries_language_normalized_term");

                    b.ToTable("vocabulary_entries", (string)null);
                });

            modelBuilder.Entity("pulaVocab.Domain.Entities.VocabularyEntryTag", b =>
                {
                    b.Property<Guid>("VocabularyEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("vocabulary_entry_id");

                    b.Property<Guid>("VocabularyTagId")
                        .HasColumnType("uuid")
                        .HasColumnName("vocabulary_tag_id");

                    b.HasKey("VocabularyEntryId", "VocabularyTagId");

                    b.HasIndex("VocabularyTagId");

                    b.ToTable("vocabulary_entry_tags", (string)null);
                });

            modelBuilder.Entity("pulaVocab.Domain.Entities.VocabularyMeaning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Context")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("context");

                    b.Property<string>("Definition")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("definition");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("translation");

                    b.Property<Guid>("VocabularyEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("vocabulary_entry_id");

                    b.HasKey("Id");

                    b.HasIndex("VocabularyEntryId");

                    b.ToTable("vocabulary_meanings", (string)null);
                });

            modelBuilder.Entity("pulaVocab.Domain.Entities.VocabularyTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_vocabulary_tags_name");

                    b.ToTable("vocabulary_tags", (string)null);
                });

            modelBuilder.Entity("pulaVocab.Domain.Entities.PracticeAnswer", b =>
                {
                    b.HasOne("pulaVocab.Domain.Entities.PracticeSession", "PracticeSession")
                        .WithMany("Answers").HasForeignKey("PracticeSessionId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("pulaVocab.Domain.Entities.VocabularyEntry", "VocabularyEntry")
                        .WithMany("PracticeAnswers").HasForeignKey("VocabularyEntryId")
                        .OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("PracticeSession");
                    b.Navigation("VocabularyEntry");
                });

            modelBuilder.Entity("pulaVocab.Domain.Entities.WordPracticeProgress", b =>
                {
                    b.HasOne("pulaVocab.Domain.Entities.VocabularyEntry", "VocabularyEntry")
                        .WithOne("PracticeProgress")
                        .HasForeignKey("pulaVocab.Domain.Entities.WordPracticeProgress", "VocabularyEntryId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("VocabularyEntry");
                });

            modelBuilder.Entity("pulaVocab.Domain.Entities.EnglishWordDetails", b =>
                {
                    b.HasOne("pulaVocab.Domain.Entities.VocabularyEntry", "VocabularyEntry")
                        .WithOne("EnglishDetails")
                        .HasForeignKey("pulaVocab.Domain.Entities.EnglishWordDetails", "VocabularyEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VocabularyEntry");
                });

            modelBuilder.Entity("pulaVocab.Domain.Entities.ExampleSentence", b =>
                {
                    b.HasOne("pulaVocab.Domain.Entities.VocabularyEntry", "VocabularyEntry")
                        .WithMany("Examples")
                        .HasForeignKey("VocabularyEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VocabularyEntry");
                });

            modelBuilder.Entity("pulaVocab.Domain.Entities.GermanWordDetails", b =>
                {
                    b.HasOne("pulaVocab.Domain.Entities.VocabularyEntry", "VocabularyEntry")
                        .WithOne("GermanDetails")
                        .HasForeignKey("pulaVocab.Domain.Entities.GermanWordDetails", "VocabularyEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VocabularyEntry");
                });

            modelBuilder.Entity("pulaVocab.Domain.Entities.VocabularyEntryTag", b =>
                {
                    b.HasOne("pulaVocab.Domain.Entities.VocabularyEntry", "VocabularyEntry")
                        .WithMany("VocabularyEntryTags")
                        .HasForeignKey("VocabularyEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pulaVocab.Domain.Entities.VocabularyTag", "VocabularyTag")
                        .WithMany("VocabularyEntryTags")
                        .HasForeignKey("VocabularyTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VocabularyEntry");

                    b.Navigation("VocabularyTag");
                });

            modelBuilder.Entity("pulaVocab.Domain.Entities.VocabularyMeaning", b =>
                {
                    b.HasOne("pulaVocab.Domain.Entities.VocabularyEntry", "VocabularyEntry")
                        .WithMany("Meanings")
                        .HasForeignKey("VocabularyEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VocabularyEntry");
                });

            modelBuilder.Entity("pulaVocab.Domain.Entities.VocabularyEntry", b =>
                {
                    b.Navigation("EnglishDetails");

                    b.Navigation("Examples");

                    b.Navigation("GermanDetails");

                    b.Navigation("Meanings");

                    b.Navigation("PracticeAnswers");

                    b.Navigation("PracticeProgress");

                    b.Navigation("VocabularyEntryTags");
                });

            modelBuilder.Entity("pulaVocab.Domain.Entities.PracticeSession", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("pulaVocab.Domain.Entities.VocabularyTag", b =>
                {
                    b.Navigation("VocabularyEntryTags");
                });
#pragma warning restore 612, 618
        }
    }
}
