using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
namespace pulaVocab.Infrastructure.Migrations;

[DbContext(typeof(VocabMasterDbContext))]
[Migration("20260809193000_AddPracticeModule")]
public partial class AddPracticeModule : Migration
{
 protected override void Up(MigrationBuilder migrationBuilder)
 {
  migrationBuilder.CreateTable(name:"practice_sessions",columns:table=>new{Id=table.Column<Guid>(type:"uuid",nullable:false),UserId=table.Column<Guid>(type:"uuid",nullable:true),ParentSessionId=table.Column<Guid>(type:"uuid",nullable:true),Language=table.Column<int>(type:"integer",nullable:false),ExerciseType=table.Column<int>(type:"integer",nullable:false),StartedAtUtc=table.Column<DateTime>(type:"timestamp with time zone",nullable:false),FinishedAtUtc=table.Column<DateTime>(type:"timestamp with time zone",nullable:true),Status=table.Column<int>(type:"integer",nullable:false),ScheduledCount=table.Column<int>(type:"integer",nullable:false),PracticedCount=table.Column<int>(type:"integer",nullable:false),CorrectCount=table.Column<int>(type:"integer",nullable:false),IncorrectCount=table.Column<int>(type:"integer",nullable:false),DurationMilliseconds=table.Column<long>(type:"bigint",nullable:true),FiltersJson=table.Column<string>(type:"jsonb",nullable:false)},constraints:table=>table.PrimaryKey("PK_practice_sessions",x=>x.Id));
  migrationBuilder.CreateTable(name:"word_practice_progress",columns:table=>new{Id=table.Column<Guid>(type:"uuid",nullable:false),UserId=table.Column<Guid>(type:"uuid",nullable:true),VocabularyEntryId=table.Column<Guid>(type:"uuid",nullable:false),FirstReviewedAtUtc=table.Column<DateTime>(type:"timestamp with time zone",nullable:true),LastReviewedAtUtc=table.Column<DateTime>(type:"timestamp with time zone",nullable:true),NextReviewAtUtc=table.Column<DateTime>(type:"timestamp with time zone",nullable:true),IntervalDays=table.Column<double>(type:"double precision",nullable:false),CorrectCount=table.Column<int>(type:"integer",nullable:false),IncorrectCount=table.Column<int>(type:"integer",nullable:false),CorrectStreak=table.Column<int>(type:"integer",nullable:false),MasteryLevel=table.Column<int>(type:"integer",nullable:false),LastRating=table.Column<int>(type:"integer",nullable:true),LastExerciseType=table.Column<int>(type:"integer",nullable:true)},constraints:table=>{table.PrimaryKey("PK_word_practice_progress",x=>x.Id);table.ForeignKey("FK_word_practice_progress_vocabulary_entries_VocabularyEntryId",x=>x.VocabularyEntryId,"vocabulary_entries","id",onDelete:ReferentialAction.Cascade);});
  migrationBuilder.CreateTable(name:"practice_answers",columns:table=>new{Id=table.Column<Guid>(type:"uuid",nullable:false),PracticeSessionId=table.Column<Guid>(type:"uuid",nullable:false),VocabularyEntryId=table.Column<Guid>(type:"uuid",nullable:false),ExerciseType=table.Column<int>(type:"integer",nullable:false),Answer=table.Column<string>(type:"character varying(500)",maxLength:500,nullable:false),IsCorrect=table.Column<bool>(type:"boolean",nullable:false),AnsweredAtUtc=table.Column<DateTime>(type:"timestamp with time zone",nullable:false),AttemptNumber=table.Column<int>(type:"integer",nullable:false),ResponseTimeMilliseconds=table.Column<long>(type:"bigint",nullable:true)},constraints:table=>{table.PrimaryKey("PK_practice_answers",x=>x.Id);table.ForeignKey("FK_practice_answers_practice_sessions_PracticeSessionId",x=>x.PracticeSessionId,"practice_sessions","Id",onDelete:ReferentialAction.Cascade);table.ForeignKey("FK_practice_answers_vocabulary_entries_VocabularyEntryId",x=>x.VocabularyEntryId,"vocabulary_entries","id",onDelete:ReferentialAction.Restrict);});
  migrationBuilder.CreateIndex("IX_practice_sessions_Status","practice_sessions","Status");migrationBuilder.CreateIndex("IX_practice_sessions_UserId_StartedAtUtc","practice_sessions",new[]{"UserId","StartedAtUtc"});migrationBuilder.CreateIndex("IX_practice_answers_VocabularyEntryId","practice_answers","VocabularyEntryId");migrationBuilder.CreateIndex("IX_practice_answers_PracticeSessionId_VocabularyEntryId_AttemptNumber","practice_answers",new[]{"PracticeSessionId","VocabularyEntryId","AttemptNumber"},unique:true);migrationBuilder.CreateIndex("IX_word_practice_progress_NextReviewAtUtc","word_practice_progress","NextReviewAtUtc");migrationBuilder.CreateIndex("IX_word_practice_progress_VocabularyEntryId","word_practice_progress","VocabularyEntryId",unique:true);migrationBuilder.CreateIndex("IX_word_practice_progress_UserId_VocabularyEntryId","word_practice_progress",new[]{"UserId","VocabularyEntryId"},unique:true);
 }
 protected override void Down(MigrationBuilder migrationBuilder){migrationBuilder.DropTable("practice_answers");migrationBuilder.DropTable("word_practice_progress");migrationBuilder.DropTable("practice_sessions");}
}
